// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateVendorData(ctx context.Context, arg CreateVendorDataParams) (VendorDatum, error)
	DeleteVendorData(ctx context.Context, id int64) error
	GetVendorData(ctx context.Context, name string) (GetVendorDataRow, error)
	UpdateVendorData(ctx context.Context, arg UpdateVendorDataParams) (VendorDatum, error)
}

var _ Querier = (*Queries)(nil)
