// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO
  instances (name, project, source_node, ip_address)
VALUES
  (?, ?, ?, ?) ON CONFLICT(name, project) DO
UPDATE
SET
  ip_address = excluded.ip_address,
  source_node = excluded.source_node,
  deleted_at = NULL,
  updated_at = CURRENT_TIMESTAMP RETURNING id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
`

type CreateInstanceParams struct {
	Name       string
	Project    string
	SourceNode string
	IpAddress  *string
}

// ===== INSTANCES QUERIES =====
func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.queryRow(ctx, q.createInstanceStmt, createInstance,
		arg.Name,
		arg.Project,
		arg.SourceNode,
		arg.IpAddress,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.SourceNode,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createInstanceLog = `-- name: CreateInstanceLog :one
INSERT INTO
  instance_logs (instance_id, log_type, level, message)
VALUES
  (?, ?, ?, ?) RETURNING id, instance_id, log_type, level, message, created_at
`

type CreateInstanceLogParams struct {
	InstanceID int64
	LogType    string
	Level      string
	Message    string
}

// ===== INSTANCE LOGS QUERIES =====
func (q *Queries) CreateInstanceLog(ctx context.Context, arg CreateInstanceLogParams) (InstanceLog, error) {
	row := q.queryRow(ctx, q.createInstanceLogStmt, createInstanceLog,
		arg.InstanceID,
		arg.LogType,
		arg.Level,
		arg.Message,
	)
	var i InstanceLog
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.LogType,
		&i.Level,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createOrUpdateInstanceMetadata = `-- name: CreateOrUpdateInstanceMetadata :one
INSERT INTO
  instance_metadata (instance_id, metadata)
VALUES
  (?, ?) ON CONFLICT(instance_id) DO
UPDATE
SET
  metadata = excluded.metadata,
  updated_at = CURRENT_TIMESTAMP RETURNING id, instance_id, metadata, updated_at
`

type CreateOrUpdateInstanceMetadataParams struct {
	InstanceID int64
	Metadata   interface{}
}

// ===== INSTANCE METADATA QUERIES =====
func (q *Queries) CreateOrUpdateInstanceMetadata(ctx context.Context, arg CreateOrUpdateInstanceMetadataParams) (InstanceMetadatum, error) {
	row := q.queryRow(ctx, q.createOrUpdateInstanceMetadataStmt, createOrUpdateInstanceMetadata, arg.InstanceID, arg.Metadata)
	var i InstanceMetadatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdateInstanceNetworkConfig = `-- name: CreateOrUpdateInstanceNetworkConfig :one
INSERT INTO
  instance_network_config (instance_id, network_config)
VALUES
  (?, ?) ON CONFLICT(instance_id) DO
UPDATE
SET
  network_config = excluded.network_config,
  updated_at = CURRENT_TIMESTAMP RETURNING id, instance_id, network_config, updated_at
`

type CreateOrUpdateInstanceNetworkConfigParams struct {
	InstanceID    int64
	NetworkConfig interface{}
}

// ===== INSTANCE NETWORK CONFIG QUERIES =====
func (q *Queries) CreateOrUpdateInstanceNetworkConfig(ctx context.Context, arg CreateOrUpdateInstanceNetworkConfigParams) (InstanceNetworkConfig, error) {
	row := q.queryRow(ctx, q.createOrUpdateInstanceNetworkConfigStmt, createOrUpdateInstanceNetworkConfig, arg.InstanceID, arg.NetworkConfig)
	var i InstanceNetworkConfig
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.NetworkConfig,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdateInstanceState = `-- name: CreateOrUpdateInstanceState :one
INSERT INTO
  instance_state (instance_id, status, status_code, updated_at)
VALUES
  (?, ?, ?, CURRENT_TIMESTAMP) ON CONFLICT(instance_id) DO
UPDATE
SET
  status = excluded.status,
  status_code = excluded.status_code,
  updated_at = CURRENT_TIMESTAMP RETURNING id, instance_id, status, status_code, updated_at
`

type CreateOrUpdateInstanceStateParams struct {
	InstanceID int64
	Status     string
	StatusCode int64
}

// ===== INSTANCE STATE QUERIES =====
func (q *Queries) CreateOrUpdateInstanceState(ctx context.Context, arg CreateOrUpdateInstanceStateParams) (InstanceState, error) {
	row := q.queryRow(ctx, q.createOrUpdateInstanceStateStmt, createOrUpdateInstanceState, arg.InstanceID, arg.Status, arg.StatusCode)
	var i InstanceState
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Status,
		&i.StatusCode,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdateInstanceUserData = `-- name: CreateOrUpdateInstanceUserData :one
INSERT INTO
  instance_user_data (instance_id, user_data)
VALUES
  (?, ?) ON CONFLICT(instance_id) DO
UPDATE
SET
  user_data = excluded.user_data,
  updated_at = CURRENT_TIMESTAMP RETURNING id, instance_id, user_data, updated_at
`

type CreateOrUpdateInstanceUserDataParams struct {
	InstanceID int64
	UserData   interface{}
}

// ===== INSTANCE USER DATA QUERIES =====
func (q *Queries) CreateOrUpdateInstanceUserData(ctx context.Context, arg CreateOrUpdateInstanceUserDataParams) (InstanceUserDatum, error) {
	row := q.queryRow(ctx, q.createOrUpdateInstanceUserDataStmt, createOrUpdateInstanceUserData, arg.InstanceID, arg.UserData)
	var i InstanceUserDatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.UserData,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrUpdateInstanceVendorData = `-- name: CreateOrUpdateInstanceVendorData :one
INSERT INTO
  instance_vendor_data (instance_id, vendor_data)
VALUES
  (?, ?) ON CONFLICT(instance_id) DO
UPDATE
SET
  vendor_data = excluded.vendor_data,
  updated_at = CURRENT_TIMESTAMP RETURNING id, instance_id, vendor_data, updated_at
`

type CreateOrUpdateInstanceVendorDataParams struct {
	InstanceID int64
	VendorData interface{}
}

// ===== INSTANCE VENDOR DATA QUERIES =====
func (q *Queries) CreateOrUpdateInstanceVendorData(ctx context.Context, arg CreateOrUpdateInstanceVendorDataParams) (InstanceVendorDatum, error) {
	row := q.queryRow(ctx, q.createOrUpdateInstanceVendorDataStmt, createOrUpdateInstanceVendorData, arg.InstanceID, arg.VendorData)
	var i InstanceVendorDatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.VendorData,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO
  profiles (name, project)
VALUES
  (?, ?) RETURNING id, name, project, created_at, updated_at, deleted_at
`

type CreateProfileParams struct {
	Name    string
	Project string
}

// ===== PROFILES QUERIES =====
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.queryRow(ctx, q.createProfileStmt, createProfile, arg.Name, arg.Project)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createVendorData = `-- name: CreateVendorData :one
INSERT INTO
  vendor_data (name, description, data)
VALUES
  (?, ?, ?) RETURNING id, name, description, created_at, updated_at, deleted_at, data
`

type CreateVendorDataParams struct {
	Name        string
	Description *string
	Data        interface{}
}

func (q *Queries) CreateVendorData(ctx context.Context, arg CreateVendorDataParams) (VendorDatum, error) {
	row := q.queryRow(ctx, q.createVendorDataStmt, createVendorData, arg.Name, arg.Description, arg.Data)
	var i VendorDatum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Data,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
UPDATE
  instances
SET
  deleted_at = CURRENT_TIMESTAMP
WHERE
  id = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteInstanceStmt, deleteInstance, id)
	return err
}

const deleteInstanceLogs = `-- name: DeleteInstanceLogs :exec
DELETE FROM
  instance_logs
WHERE
  instance_id = ?
`

func (q *Queries) DeleteInstanceLogs(ctx context.Context, instanceID int64) error {
	_, err := q.exec(ctx, q.deleteInstanceLogsStmt, deleteInstanceLogs, instanceID)
	return err
}

const deleteInstanceMetadata = `-- name: DeleteInstanceMetadata :exec
DELETE FROM
  instance_metadata
WHERE
  instance_id = ?
`

func (q *Queries) DeleteInstanceMetadata(ctx context.Context, instanceID int64) error {
	_, err := q.exec(ctx, q.deleteInstanceMetadataStmt, deleteInstanceMetadata, instanceID)
	return err
}

const deleteInstanceNetworkConfig = `-- name: DeleteInstanceNetworkConfig :exec
DELETE FROM
  instance_network_config
WHERE
  instance_id = ?
`

func (q *Queries) DeleteInstanceNetworkConfig(ctx context.Context, instanceID int64) error {
	_, err := q.exec(ctx, q.deleteInstanceNetworkConfigStmt, deleteInstanceNetworkConfig, instanceID)
	return err
}

const deleteInstanceState = `-- name: DeleteInstanceState :exec
DELETE FROM
  instance_state
WHERE
  instance_id = ?
`

func (q *Queries) DeleteInstanceState(ctx context.Context, instanceID int64) error {
	_, err := q.exec(ctx, q.deleteInstanceStateStmt, deleteInstanceState, instanceID)
	return err
}

const deleteInstanceUserData = `-- name: DeleteInstanceUserData :exec
DELETE FROM
  instance_user_data
WHERE
  instance_id = ?
`

func (q *Queries) DeleteInstanceUserData(ctx context.Context, instanceID int64) error {
	_, err := q.exec(ctx, q.deleteInstanceUserDataStmt, deleteInstanceUserData, instanceID)
	return err
}

const deleteInstanceVendorData = `-- name: DeleteInstanceVendorData :exec
DELETE FROM
  instance_vendor_data
WHERE
  instance_id = ?
`

func (q *Queries) DeleteInstanceVendorData(ctx context.Context, instanceID int64) error {
	_, err := q.exec(ctx, q.deleteInstanceVendorDataStmt, deleteInstanceVendorData, instanceID)
	return err
}

const deleteOldInstanceLogs = `-- name: DeleteOldInstanceLogs :exec
DELETE FROM
  instance_logs
WHERE
  created_at < ?
  AND instance_id = ?
`

type DeleteOldInstanceLogsParams struct {
	CreatedAt  *time.Time
	InstanceID int64
}

func (q *Queries) DeleteOldInstanceLogs(ctx context.Context, arg DeleteOldInstanceLogsParams) error {
	_, err := q.exec(ctx, q.deleteOldInstanceLogsStmt, deleteOldInstanceLogs, arg.CreatedAt, arg.InstanceID)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
UPDATE
  profiles
SET
  deleted_at = CURRENT_TIMESTAMP
WHERE
  id = ?
`

func (q *Queries) DeleteProfile(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteProfileStmt, deleteProfile, id)
	return err
}

const deleteVendorData = `-- name: DeleteVendorData :exec
UPDATE
  vendor_data
SET
  deleted_at = CURRENT_TIMESTAMP
WHERE
  id = ?
`

func (q *Queries) DeleteVendorData(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteVendorDataStmt, deleteVendorData, id)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT
  id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
FROM
  instances
WHERE
  name = ?
  AND project = ?
  AND deleted_at IS NULL
`

type GetInstanceParams struct {
	Name    string
	Project string
}

func (q *Queries) GetInstance(ctx context.Context, arg GetInstanceParams) (Instance, error) {
	row := q.queryRow(ctx, q.getInstanceStmt, getInstance, arg.Name, arg.Project)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.SourceNode,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceByID = `-- name: GetInstanceByID :one
SELECT
  id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
FROM
  instances
WHERE
  id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetInstanceByID(ctx context.Context, id int64) (Instance, error) {
	row := q.queryRow(ctx, q.getInstanceByIDStmt, getInstanceByID, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.SourceNode,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceByIP = `-- name: GetInstanceByIP :one
SELECT
  id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
FROM
  instances
WHERE
  ip_address = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetInstanceByIP(ctx context.Context, ipAddress *string) (Instance, error) {
	row := q.queryRow(ctx, q.getInstanceByIPStmt, getInstanceByIP, ipAddress)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.SourceNode,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceLogs = `-- name: GetInstanceLogs :many
SELECT
  id, instance_id, log_type, level, message, created_at
FROM
  instance_logs
WHERE
  instance_id = ?
ORDER BY
  created_at DESC
LIMIT
  ? OFFSET ?
`

type GetInstanceLogsParams struct {
	InstanceID int64
	Limit      int64
	Offset     int64
}

func (q *Queries) GetInstanceLogs(ctx context.Context, arg GetInstanceLogsParams) ([]InstanceLog, error) {
	rows, err := q.query(ctx, q.getInstanceLogsStmt, getInstanceLogs, arg.InstanceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceLog
	for rows.Next() {
		var i InstanceLog
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.LogType,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstanceLogsByLevel = `-- name: GetInstanceLogsByLevel :many
SELECT
  id, instance_id, log_type, level, message, created_at
FROM
  instance_logs
WHERE
  instance_id = ?
  AND level = ?
ORDER BY
  created_at DESC
LIMIT
  ? OFFSET ?
`

type GetInstanceLogsByLevelParams struct {
	InstanceID int64
	Level      string
	Limit      int64
	Offset     int64
}

func (q *Queries) GetInstanceLogsByLevel(ctx context.Context, arg GetInstanceLogsByLevelParams) ([]InstanceLog, error) {
	rows, err := q.query(ctx, q.getInstanceLogsByLevelStmt, getInstanceLogsByLevel,
		arg.InstanceID,
		arg.Level,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceLog
	for rows.Next() {
		var i InstanceLog
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.LogType,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstanceLogsByType = `-- name: GetInstanceLogsByType :many
SELECT
  id, instance_id, log_type, level, message, created_at
FROM
  instance_logs
WHERE
  instance_id = ?
  AND log_type = ?
ORDER BY
  created_at DESC
LIMIT
  ? OFFSET ?
`

type GetInstanceLogsByTypeParams struct {
	InstanceID int64
	LogType    string
	Limit      int64
	Offset     int64
}

func (q *Queries) GetInstanceLogsByType(ctx context.Context, arg GetInstanceLogsByTypeParams) ([]InstanceLog, error) {
	rows, err := q.query(ctx, q.getInstanceLogsByTypeStmt, getInstanceLogsByType,
		arg.InstanceID,
		arg.LogType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceLog
	for rows.Next() {
		var i InstanceLog
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.LogType,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstanceMetadata = `-- name: GetInstanceMetadata :one
SELECT
  id, instance_id, metadata, updated_at
FROM
  instance_metadata
WHERE
  instance_id = ?
`

func (q *Queries) GetInstanceMetadata(ctx context.Context, instanceID int64) (InstanceMetadatum, error) {
	row := q.queryRow(ctx, q.getInstanceMetadataStmt, getInstanceMetadata, instanceID)
	var i InstanceMetadatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceMetadataByIP = `-- name: GetInstanceMetadataByIP :one
SELECT
  im.id, im.instance_id, im.metadata, im.updated_at
FROM
  instance_metadata im
  JOIN instances i ON im.instance_id = i.id
WHERE
  i.ip_address = ?
  AND i.deleted_at IS NULL
`

func (q *Queries) GetInstanceMetadataByIP(ctx context.Context, ipAddress *string) (InstanceMetadatum, error) {
	row := q.queryRow(ctx, q.getInstanceMetadataByIPStmt, getInstanceMetadataByIP, ipAddress)
	var i InstanceMetadatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Metadata,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceNetworkConfig = `-- name: GetInstanceNetworkConfig :one
SELECT
  id, instance_id, network_config, updated_at
FROM
  instance_network_config
WHERE
  instance_id = ?
`

func (q *Queries) GetInstanceNetworkConfig(ctx context.Context, instanceID int64) (InstanceNetworkConfig, error) {
	row := q.queryRow(ctx, q.getInstanceNetworkConfigStmt, getInstanceNetworkConfig, instanceID)
	var i InstanceNetworkConfig
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.NetworkConfig,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceNetworkConfigByIP = `-- name: GetInstanceNetworkConfigByIP :one
SELECT
  inc.id, inc.instance_id, inc.network_config, inc.updated_at
FROM
  instance_network_config inc
  JOIN instances i ON inc.instance_id = i.id
WHERE
  i.ip_address = ?
  AND i.deleted_at IS NULL
`

func (q *Queries) GetInstanceNetworkConfigByIP(ctx context.Context, ipAddress *string) (InstanceNetworkConfig, error) {
	row := q.queryRow(ctx, q.getInstanceNetworkConfigByIPStmt, getInstanceNetworkConfigByIP, ipAddress)
	var i InstanceNetworkConfig
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.NetworkConfig,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceState = `-- name: GetInstanceState :one
SELECT
  id, instance_id, status, status_code, updated_at
FROM
  instance_state
WHERE
  instance_id = ?
`

func (q *Queries) GetInstanceState(ctx context.Context, instanceID int64) (InstanceState, error) {
	row := q.queryRow(ctx, q.getInstanceStateStmt, getInstanceState, instanceID)
	var i InstanceState
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Status,
		&i.StatusCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceUserData = `-- name: GetInstanceUserData :one
SELECT
  id, instance_id, user_data, updated_at
FROM
  instance_user_data
WHERE
  instance_id = ?
`

func (q *Queries) GetInstanceUserData(ctx context.Context, instanceID int64) (InstanceUserDatum, error) {
	row := q.queryRow(ctx, q.getInstanceUserDataStmt, getInstanceUserData, instanceID)
	var i InstanceUserDatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.UserData,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceUserDataByIP = `-- name: GetInstanceUserDataByIP :one
SELECT
  iud.id, iud.instance_id, iud.user_data, iud.updated_at
FROM
  instance_user_data iud
  JOIN instances i ON iud.instance_id = i.id
WHERE
  i.ip_address = ?
  AND i.deleted_at IS NULL
`

func (q *Queries) GetInstanceUserDataByIP(ctx context.Context, ipAddress *string) (InstanceUserDatum, error) {
	row := q.queryRow(ctx, q.getInstanceUserDataByIPStmt, getInstanceUserDataByIP, ipAddress)
	var i InstanceUserDatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.UserData,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceVendorData = `-- name: GetInstanceVendorData :one
SELECT
  id, instance_id, vendor_data, updated_at
FROM
  instance_vendor_data
WHERE
  instance_id = ?
`

func (q *Queries) GetInstanceVendorData(ctx context.Context, instanceID int64) (InstanceVendorDatum, error) {
	row := q.queryRow(ctx, q.getInstanceVendorDataStmt, getInstanceVendorData, instanceID)
	var i InstanceVendorDatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.VendorData,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceVendorDataByIP = `-- name: GetInstanceVendorDataByIP :one
SELECT
  ivd.id, ivd.instance_id, ivd.vendor_data, ivd.updated_at
FROM
  instance_vendor_data ivd
  JOIN instances i ON ivd.instance_id = i.id
WHERE
  i.ip_address = ?
  AND i.deleted_at IS NULL
`

func (q *Queries) GetInstanceVendorDataByIP(ctx context.Context, ipAddress *string) (InstanceVendorDatum, error) {
	row := q.queryRow(ctx, q.getInstanceVendorDataByIPStmt, getInstanceVendorDataByIP, ipAddress)
	var i InstanceVendorDatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.VendorData,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT
  id, name, project, created_at, updated_at, deleted_at
FROM
  profiles
WHERE
  name = ?
  AND project = ?
  AND deleted_at IS NULL
`

type GetProfileParams struct {
	Name    string
	Project string
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (Profile, error) {
	row := q.queryRow(ctx, q.getProfileStmt, getProfile, arg.Name, arg.Project)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVendorData = `-- name: GetVendorData :one
SELECT
  id,
  name,
  description,
  created_at,
  updated_at,
  data
FROM
  vendor_data
WHERE
  name = ?
  and deleted_at IS NULL
`

type GetVendorDataRow struct {
	ID          int64
	Name        string
	Description *string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	Data        interface{}
}

func (q *Queries) GetVendorData(ctx context.Context, name string) (GetVendorDataRow, error) {
	row := q.queryRow(ctx, q.getVendorDataStmt, getVendorData, name)
	var i GetVendorDataRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Data,
	)
	return i, err
}

const hardDeleteInstance = `-- name: HardDeleteInstance :exec
DELETE FROM
  instances
WHERE
  id = ?
`

func (q *Queries) HardDeleteInstance(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.hardDeleteInstanceStmt, hardDeleteInstance, id)
	return err
}

const listActiveInstancesBySourceNode = `-- name: ListActiveInstancesBySourceNode :many
SELECT
  id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
FROM
  instances
WHERE
  source_node = ?
  AND deleted_at IS NULL
`

func (q *Queries) ListActiveInstancesBySourceNode(ctx context.Context, sourceNode string) ([]Instance, error) {
	rows, err := q.query(ctx, q.listActiveInstancesBySourceNodeStmt, listActiveInstancesBySourceNode, sourceNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.SourceNode,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstances = `-- name: ListInstances :many
SELECT
  id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
FROM
  instances
WHERE
  deleted_at IS NULL
ORDER BY
  created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.query(ctx, q.listInstancesStmt, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.SourceNode,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByProject = `-- name: ListInstancesByProject :many
SELECT
  id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
FROM
  instances
WHERE
  project = ?
  AND deleted_at IS NULL
ORDER BY
  created_at DESC
`

func (q *Queries) ListInstancesByProject(ctx context.Context, project string) ([]Instance, error) {
	rows, err := q.query(ctx, q.listInstancesByProjectStmt, listInstancesByProject, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.SourceNode,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfiles = `-- name: ListProfiles :many
SELECT
  id, name, project, created_at, updated_at, deleted_at
FROM
  profiles
WHERE
  deleted_at IS NULL
ORDER BY
  created_at DESC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.query(ctx, q.listProfilesStmt, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByProject = `-- name: ListProfilesByProject :many
SELECT
  id, name, project, created_at, updated_at, deleted_at
FROM
  profiles
WHERE
  project = ?
  AND deleted_at IS NULL
ORDER BY
  created_at DESC
`

func (q *Queries) ListProfilesByProject(ctx context.Context, project string) ([]Profile, error) {
	rows, err := q.query(ctx, q.listProfilesByProjectStmt, listProfilesByProject, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Project,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstance = `-- name: UpdateInstance :one
UPDATE
  instances
SET
  ip_address = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, name, project, source_node, ip_address, created_at, updated_at, deleted_at
`

type UpdateInstanceParams struct {
	IpAddress *string
	ID        int64
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error) {
	row := q.queryRow(ctx, q.updateInstanceStmt, updateInstance, arg.IpAddress, arg.ID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.SourceNode,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInstanceIP = `-- name: UpdateInstanceIP :exec
UPDATE
  instances
SET
  ip_address = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ?
`

type UpdateInstanceIPParams struct {
	IpAddress *string
	ID        int64
}

func (q *Queries) UpdateInstanceIP(ctx context.Context, arg UpdateInstanceIPParams) error {
	_, err := q.exec(ctx, q.updateInstanceIPStmt, updateInstanceIP, arg.IpAddress, arg.ID)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE
  profiles
SET
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, name, project, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateProfile(ctx context.Context, id int64) (Profile, error) {
	row := q.queryRow(ctx, q.updateProfileStmt, updateProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Project,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateVendorData = `-- name: UpdateVendorData :one
UPDATE
  vendor_data
SET
  description = ?,
  data = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, name, description, created_at, updated_at, deleted_at, data
`

type UpdateVendorDataParams struct {
	Description *string
	Data        interface{}
	ID          int64
}

func (q *Queries) UpdateVendorData(ctx context.Context, arg UpdateVendorDataParams) (VendorDatum, error) {
	row := q.queryRow(ctx, q.updateVendorDataStmt, updateVendorData, arg.Description, arg.Data, arg.ID)
	var i VendorDatum
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Data,
	)
	return i, err
}
